### ISSUE TITLE
Invalid ScheduleExpression

### ISSUE THREAD

**Issue by Sebelino** [buildkite/image-builder#7]
The default value for `ScheduleExpression` looks invalid, as I am getting the following when creating the stack:
```
Resource handler returned message: "The value supplied for parameter 'schedule.scheduleExpression' is not valid. Invalid schedule expression. Details: Invalid CRON expression: error at position 9, details: Unexpected end of expression.
```

**Comment by pda** [comment]
“How did that ever work?” :)

Looks like it _did_ used to work, but EC2 Image Builder changed their syntax early 2021.
I can't find an official change announcement, but this Terraform AWS provider issue gives some hints:
https://github.com/hashicorp/terraform-provider-aws/issues/17396

Thanks for the fix in #8 👍🏼

**Comment by pda** [comment]
We had an Image Builder in us-east-1 successfully using the previous syntax until March 2022, at which point it silently stopped working. So I guess this change gradually rolled out across regions/accounts/something.

**Comment by synth** [comment]
Thanks for the fix. Respectfully, can you update the template on s3 as it still has the old syntax which I got bit by. Cheers.
